version: "3"

services:
  laravel:
    build:
      context: ./
      dockerfile: ./docker/laravel/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www

  web:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www

  db:
    image: postgres:15
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    restart: unless-stopped
    tty: true

volumes:
  database:
